---

- hosts: engine
  remote_user: root
  gather_facts: no
  roles:
    - wait_for_host_up
    - override_tty
    - { role: subscription, when: '{{ repositories|length > 0 }}'}
    - wait_for_yum_lock
    - engine
    - { role: wait_for_engine, tags: ['config'] }
    - datacenter

- hosts: hypervisors
  remote_user: root
  gather_facts: no
  roles:
    - wait_for_host_up
    - override_tty
    - { role: subscription, when: '{{ repositories|length > 0 }}'}
    - wait_for_yum_lock
    - hypervisor
    - { role: wait_for_engine, tags: ['config'] }
    - { role: register_hypervisor, script_runner: '{{ engine_fqdn }}' }

- hosts: engine
  remote_user: root
  roles:
    - { role: wait_for_engine, tags: ['config'] }
    - storage
    - wait_for_datacenter
