---

- hosts: engine
  strategy: debug
  remote_user: root
  pre_tasks:
    - name: authenticate to engine
      ovirt_auth:
        username: '{{ engine_username }}'
        password: '{{ admin_password }}'
        url: https://{{ engine_fqdn }}/ovirt-engine/api
        insecure: true
  roles:
    - wait_for_host_up
    - { role: launch_vms, when: '{{ vms is defined }}' }
